### ISSUE TITLE
Example for MQTT implementation

### ISSUE THREAD

**Issue by pierrejochem** [samsonasik/ErrorHeroModule#34]
Dear Abdul,

could you give an example how I can intregrate a MQTT writer to the logic. Maybe in the README.md?

I would support you If you give me a hint.

Thank you 

Cheers

Pierre

**Comment by samsonasik** [comment]
Hi @pierrejochem,

First, you can create a custom `Writer` which you can inherit from `Zend\Log\Writer\AbstractWriter`, then register the new writer under `log_writers` config, e.g.:

```php
// config/autoload/global.php
return [
   // ...
   'log_writers' => [
           'factories' =>  [
                 \Application\Writer\Mqtt::class => \Application\Writer\MqttFactory::class,
          ],
  ],
];
```

Next, ensure `Zend\Log` registered at `config/application.config.php` or `config/modules.config.php` before `ErrorHeroModule`.

Last, register the Mqtt writer under `log` => `ErrorHeroModuleLogger` => `writers` after 'db'.

```php
'log' => [
        'ErrorHeroModuleLogger' => [
            'writers' => [

                [
                    'name' => 'db',
                    'options' => [
                         // ...
                    ],
                ],

                [
                        'name' =>  \Application\Writer\Mqtt::class,
                        'options' => [
                                 // ...
                        ]
                ],

            ],
        ],
    ],
```

**Comment by pierrejochem** [comment]
Thank you 👍 Will try it right now.

**Comment by pierrejochem** [comment]
Easy going :-) Works like a champ 👍
