### ISSUE TITLE
Wrong format of timestamp

### ISSUE THREAD

**Issue by VadimIzmalkov** [samsonasik/ErrorHeroModule#41]
What ZF application I'm using when issue happen ?

- [x] ^ZF2.5
- [ ] ^ZF3
- [ ] Expressive 1
- [ ] Expressive 2
- [ ] Expressive 3

What PHP version you're using?

- [ ] PHP 5.6
- [x] PHP 7.0
- [ ] PHP 7.1
- [ ] PHP 7.2

What ErrorHeroModule version you're using?

- [x] ^1.0
- [ ] ^2.0

### Expected behavior
Write logs to database. 

### Actual behavior
Nothing happens in database once bug has been occured. 

### Explanation
Method $this->getDateTimeFormat() https://github.com/samsonasik/ErrorHeroModule/blob/master/src/Handler/Formatter/Json.php#L26 return timestamp in "c" format 2004-02-12T15:19:21+00:00 . On my preset Mysql requires "Y-m-d H:i:s"

### Workaround
Change type of 'date' to text

**Comment by samsonasik** [comment]
In that case, you can setup your log config to add "formatters" with the following under "options" db writers config: 

```php 
    'log' => [
        'ErrorHeroModuleLogger' => [
            'writers' => [

                [
                    'name' => 'db',
                    'options' => [
                        // ... current config
                        'formatter' => [
                             'name' => 'db',
                             'options' => [
                                  'dateTimeFormat' => 'Y-m-d H:i:s',
                             ],
                         ],
                      // ...
                    ],
                ],

            ],
        ],
    ],
```

**Comment by VadimIzmalkov** [comment]
Thanks, it work for me
