### ISSUE TITLE
error-hero-module downgrades from 2.16.0 to 2.3.0 when I update beberlei/assert to v3.1.0

### ISSUE THREAD

**Issue by dennis-fedco** [samsonasik/ErrorHeroModule#59]
What ZF application I'm using when issue happen ?
- [x] Expressive 3

What PHP version you're using?
- [x] PHP 7.1

What ErrorHeroModule version you're using?
- [x] ^2.0

What Database you're using?

- [x] MySQL version ...

### Expected behavior
Not downgrading samsonasik/error-hero-module from 2.16.0 to 2.3.0.

### Actual behavior
composer Downgrading samsonasik/error-hero-module (2.16.0 => 2.3.0)

### Steps/Codes to reproduce the behavior
1. Update `beberlei/assert` from ` v2.9.6` to `v3.1.0` in composer.json file,
while having `samsonasik/error-hero-module (2.16.0)`
2. Run composer update

**Comment by samsonasik** [comment]
@dennis-fedco thank you. It should be fixed at https://github.com/samsonasik/ErrorHeroModule/commit/57a91aa4a794c6b34b04f9a151d64fdc8aa36c92 .
