### ISSUE TITLE
Can't update my composer since weeks

### ISSUE THREAD

**Issue by juliangorge** [samsonasik/ErrorHeroModule#95]
Hello! I have many projects with this module and I have problems with update my packages. I have tried to create a new Laminas project but it is not still work.
Also I tried to install specific 3.1.1 version (compatible with PHP 7).

`composer require samsonasik/error-hero-module  
Using version ^3.1 for samsonasik/error-hero-module
./composer.json has been updated
Running composer update samsonasik/error-hero-module
Loading composer repositories with package information
Updating dependencies                                 
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - laminas/laminas-diactoros[2.18.0, ..., 2.25.2] require php ~8.0.0 || ~8.1.0 || ~8.2.0 -> your php version (7.4.33) does not satisfy that requirement.
    - Root composer.json requires samsonasik/error-hero-module ^3.1 -> satisfiable by samsonasik/error-hero-module[3.1.0, 3.1.1].
    - samsonasik/error-hero-module[3.1.0, ..., 3.1.1] require laminas/laminas-diactoros ^2.0 -> satisfiable by laminas/laminas-diactoros[2.0.0, ..., 2.25.2].
    - roave/security-advisories dev-master conflicts with laminas/laminas-diactoros 2.17.0.
    - roave/security-advisories dev-master conflicts with laminas/laminas-diactoros 2.14.0.
    - roave/security-advisories dev-master conflicts with laminas/laminas-diactoros 2.6.0.
    - roave/security-advisories dev-master conflicts with laminas/laminas-diactoros 2.4.1.
    - roave/security-advisories dev-master conflicts with laminas/laminas-diactoros 2.2.2.
    - roave/security-advisories dev-master conflicts with laminas/laminas-diactoros 2.2.1p2.
    - roave/security-advisories dev-master conflicts with laminas/laminas-diactoros 2.2.1p1.
    - roave/security-advisories dev-master conflicts with laminas/laminas-diactoros 2.2.1.
    - roave/security-advisories dev-master conflicts with laminas/laminas-diactoros 2.2.0p2.
    - roave/security-advisories dev-master conflicts with laminas/laminas-diactoros 2.2.0p1.
    - roave/security-advisories dev-master conflicts with laminas/laminas-diactoros 2.2.0.
    - roave/security-advisories dev-master conflicts with laminas/laminas-diactoros 2.1.5p2.
    - roave/security-advisories dev-master conflicts with laminas/laminas-diactoros 2.1.5p1.
    - roave/security-advisories dev-master conflicts with laminas/laminas-diactoros 2.1.5.
    - roave/security-advisories dev-master conflicts with laminas/laminas-diactoros 2.1.4p2.
    - roave/security-advisories dev-master conflicts with laminas/laminas-diactoros 2.1.4p1.
    - roave/security-advisories dev-master conflicts with laminas/laminas-diactoros 2.1.4.
    - roave/security-advisories dev-master conflicts with laminas/laminas-diactoros 2.1.3p2.
    - roave/security-advisories dev-master conflicts with laminas/laminas-diactoros 2.1.3p1.
    - roave/security-advisories dev-master conflicts with laminas/laminas-diactoros 2.1.3.
    - roave/security-advisories dev-master conflicts with laminas/laminas-diactoros 2.1.2p2.
    - roave/security-advisories dev-master conflicts with laminas/laminas-diactoros 2.1.2p1.
    - roave/security-advisories dev-master conflicts with laminas/laminas-diactoros 2.1.2.
    - roave/security-advisories dev-master conflicts with laminas/laminas-diactoros 2.1.1p2.
    - roave/security-advisories dev-master conflicts with laminas/laminas-diactoros 2.1.1p1.
    - roave/security-advisories dev-master conflicts with laminas/laminas-diactoros 2.1.1.
    - roave/security-advisories dev-master conflicts with laminas/laminas-diactoros 2.1.0p2.
    - roave/security-advisories dev-master conflicts with laminas/laminas-diactoros 2.1.0p1.
    - roave/security-advisories dev-master conflicts with laminas/laminas-diactoros 2.1.0.
    - roave/security-advisories dev-master conflicts with laminas/laminas-diactoros 2.0.3p2.
    - roave/security-advisories dev-master conflicts with laminas/laminas-diactoros 2.0.3p1.
    - roave/security-advisories dev-master conflicts with laminas/laminas-diactoros 2.0.3.
    - roave/security-advisories dev-master conflicts with laminas/laminas-diactoros 2.0.2p2.
    - roave/security-advisories dev-master conflicts with laminas/laminas-diactoros 2.0.2p1.
    - roave/security-advisories dev-master conflicts with laminas/laminas-diactoros 2.0.2.
    - roave/security-advisories dev-master conflicts with laminas/laminas-diactoros 2.0.1p2.
    - roave/security-advisories dev-master conflicts with laminas/laminas-diactoros 2.0.1p1.
    - roave/security-advisories dev-master conflicts with laminas/laminas-diactoros 2.0.1.
    - roave/security-advisories dev-master conflicts with laminas/laminas-diactoros 2.0.0p2.
    - roave/security-advisories dev-master conflicts with laminas/laminas-diactoros 2.0.0p1.
    - roave/security-advisories dev-master conflicts with laminas/laminas-diactoros 2.0.0.
    - roave/security-advisories is locked to version dev-master and an update of this package was not requested.

You can also try re-running composer require with an explicit version constraint, e.g. "composer require samsonasik/error-hero-module:*" to figure out if any version is installable, or "composer require samsonasik/error-hero-module:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
`
------------------------

What ZF/Expressive/Laminas/Mezzio application I'm using when issue happen ?
- [X ] Laminas 3

What PHP version you're using?
- [X ] PHP 7.4

What ErrorHeroModule version you're using?
- [X ] ^3.0

What Database you're using?
- [X ] MySQL version ...

**Comment by samsonasik** [comment]
It seems you define `laminas-diactoros` in your composer.json, You need downgrade to use "laminas-diactoros":"~2.17.0" in your composer.json

see on this requirement https://packagist.org/packages/laminas/laminas-diactoros#2.17.0

**Comment by juliangorge** [comment]
No, there is not

`"require": {
        "php": "^7.3 || ~8.0.0 || ~8.1.0",
        "laminas-api-tools/api-tools": "^1.6.0",
        "laminas-api-tools/api-tools-content-negotiation": "^1.6.0",
        "laminas-api-tools/api-tools-documentation": "^1.3",
        "laminas-api-tools/api-tools-rest": "^1.6.1",
        "laminas/laminas-authentication": "^2.12",
        "laminas/laminas-barcode": "^2.11",
        "laminas/laminas-cache": "^3.6",
        "laminas/laminas-captcha": "^2.13",
        "laminas/laminas-cli": "^1.5",
        "laminas/laminas-component-installer": "^2.1.1",
        "laminas/laminas-db": "^2.15",
        "laminas/laminas-development-mode": "^3.2",
        "laminas/laminas-i18n": "^2.17",
        "laminas/laminas-i18n-resources": "^2.8",
        "laminas/laminas-mvc-plugin-flashmessenger": "^1.8",
        "laminas/laminas-mvc-plugin-identity": "^1.4",
        "laminas/laminas-navigation": "^2.15",
        "laminas/laminas-permissions-acl": "^2.10",
        "laminas/laminas-progressbar": "^2.10",
        "laminas/laminas-servicemanager": "^3.17",
        "laminas/laminas-session": "^2.13",
        "laminas/laminas-soap": "^2.10",
        "laminas/laminas-view": "^2.23",
        "laminas/laminas-zendframework-bridge": "^1.0"
    },
    "require-dev": {
        "laminas-api-tools/api-tools-admin": "^2.0.1",
        "laminas-api-tools/api-tools-asset-manager": "^1.2",
        "laminas/laminas-cli": "^1.2",
        "laminas/laminas-coding-standard": "~2.3.0",
        "laminas/laminas-composer-autoloading": "^3.1",
        "laminas/laminas-developer-tools": "^2.3",
        "laminas/laminas-test": "^4.0",
        "phpunit/phpunit": "^9.5.20",
        "psalm/plugin-phpunit": "^0.16.1",
        "roave/security-advisories": "dev-master",
        "vimeo/psalm": "^4.10"
    },`

**Comment by samsonasik** [comment]
Looking at the error, it seems there is interdependency somewhere, you need to pin in composer.json:

```
"require" {
      // ...
     "laminas/laminas-diactoros": "2.17.0"
      // ...
}
```

and run composer update

**Comment by juliangorge** [comment]
Okay, I installed it. But when I run update, I have this log:

  Problem 1
    - Root composer.json requires laminas/laminas-diactoros 2.17.0 -> satisfiable by laminas/laminas-diactoros[2.17.0].
    - roave/security-advisories dev-master conflicts with laminas/laminas-diactoros <2.18.1|>=2.24,<2.24.2|>=2.25,<2.25.2|= 2.23.0|= 2.22.0|= 2.21.0|= 2.20.0|= 2.19.0.
    - Root composer.json requires roave/security-advisories dev-master -> satisfiable by roave/security-advisories[dev-master].

Do I need this roave/security-advisories?

**Comment by samsonasik** [comment]
You don't if you use old libraries, `roave/security-advisories` verify latest patch for better security, which not on your use case as you use old php version.

**Comment by juliangorge** [comment]
Thank you!
