### ISSUE TITLE
excluded errors are not excluded

### ISSUE THREAD

**Issue by pschelte-extec** [samsonasik/ErrorHeroModule#96]
What ZF/Expressive/Laminas/Mezzio application I'm using when issue happen ?

- [x] Laminas 3

What PHP version you're using?

- [x] PHP 8.1

What ErrorHeroModule version you're using?

- [x] ^5.0

What Database you're using?

- [x] Oracle 12

### Expected behavior

I have added \E_DEPRECATED error as a value of the array 'exclude-php-errors' in the config file
so E_DEPRACATED errors should be ignored.

### Actual behavior

E_DEPRECATED errors are still catched even if I have added \E_DEPRECATED error as a value of the array 'exclude-php-errors' in the config file.

### Steps/Codes to reproduce the behavior

in \config\autoload\error-hero-module.global.php

            'exclude-php-errors' => [
                \E_USER_DEPRECATED,
                \E_DEPRECATED, // <--- add this
            ],

in index.php add this at the first beginning :

`<?php 
$a = false;
$a[] = 1;`

execute index.php within your app in your browser.

the E_DEPRECATED error is catched by ErrorHeroModule.

**Comment by samsonasik** [comment]
That's expected as in index.php early line, the service is not loaded yet. This works on module level, you should not touch index.php with custom logic.

**Comment by pschelte-extec** [comment]
You are probably right, but how can you explain that the deprecated error is logged in the DB by ErrorHeroModule and that the user friendly message provided by ErrorHeroModule is displayed instead of the usual basic PHP error ?

here is the message I have in my DB reported by ErrorHeroModule : 

Automatic conversion of false to array is deprecated
/ec/prod/app/webroot/home/food/safety/food_waste/eu-food-loss-waste-prevention-hub/index.php	10	E_DEPRECATED

**Comment by samsonasik** [comment]
That's out of this module scope, again, this is on module level, index.php consume the module on this execution:

https://github.com/laminas/laminas-mvc-skeleton/blob/e4bfbffdd5c52b680f515fa4853efefd0bc6d7fa/public/index.php#L35-L36

this module doesn't covert error to message, it is for logging and trap purpose.
